name: "Setup node and install dependencies"
description: "Takes care of the copy-pasta for the cache handling of npm"
inputs:
  command:
    description: "Which command to run when installing the dependencies? It will be appended to `npm ` Default: install --no-audit --no-fund"
    default: install --no-audit --no-fund
    required: false
  cache-name:
    description: "The name of the cache to use"
    required: true

outputs:
    cache-hit:
        description: "A boolean value to indicate if a cache was hit."
        value: ${{ steps.node.outputs.cache-hit }}
    node-version:
        description: "The installed node version."
        value: ${{ steps.node.outputs.node-version }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4.0.4
      id: node
      with:
        node-version-file: package.json
        cache: 'npm'
        check-latest: true

    - name: Installing Dependencies using npm ${{ inputs.command }}
      run: npm ${{ inputs.command }}
      shell: bash
