name: "Setup node and install dependencies"
description: "Takes care of the copy-pasta for the cache handling of npm"
inputs:
  command:
    description: "Which command to run when installing the dependencies? It will be appended to `npm ` Default: install --no-audit --no-fund"
    default: install --no-audit --no-fund
    required: false
    type: string
  cache-name:
    description: "The name of the cache to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version-file: package.json
        cache: 'npm'
        check-latest: true

    - name: Installing Dependencies using npm ${{ inputs.command }}
      run: npm ${{ inputs.command }}
      shell: bash
